config/routes.rb
Rails.application.routes.draw do
  get 'search/search'

  use_doorkeeper
  resources :attachments, only: [:destroy]

  get 'search', to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles do        
        get :me, on: :collection
      end
      resources :questions
      resources :answers
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post 'email_confirmation', to: 'omniauth_callbacks#email_confirmation'
  end
  resources :votes, only: [:create, :destroy]

  concern :commentable do
    resources :comments, only: [:create]
  end

  resources :questions, concerns: :commentable do
    resources :subscribes, only: [:create, :destroy]
    resources :answers, only: [:create, :update, :destroy], concerns: :commentable do
      post :best, on: :member
    end
  end

  root 'questions#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Voteable
  include Attachable

  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :subscribes, dependent: :destroy
  belongs_to :user

  validates :title, :body, :user_id, presence: true
  validates :title, length: { minimum: 3, maximum: 150 }

  scope :yesterday, -> { where("created_at >= ?", Time.zone.now.beginning_of_day) }

  def best_answer
    self.answers.where(best: true).first
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions, each_serializer: QuestionSerializer
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question, serializer: QuestionSerializer
  end

  def create
    @question = Question.create(questions_params.merge(user: current_resource_owner))
    respond_with @question
  end

  private

  def questions_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  before_action :build_answer, only: [:show]

  respond_to :js, only: [:create, :update]

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with(@question)
  end

  def new
    respond_with(@question = Question.new)
  end

  def edit
  end

  def create
    respond_with(@question = Question.create(questions_params.merge(user: current_user)))
  end

  def update
    respond_with(@question.update(questions_params))
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def questions_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_attachment_fields.html.slim
.form-group(style="padding: 10px; border: 1px solid #cccccc; border-radius: 10px;" )
  .field
    = f.label :file, 'Файл'
    = f.file_field :file
  = link_to_remove_association "удалить файл", f

app/views/questions/_question.html.slim
.row
  .col-md-12.question-block
    h4.pull-left
      = link_to question.title, question
    h4.pull-right
      = link_to question.created_at.strftime('%d/%m/%Y в %H:%M'), question

app/views/questions/create.js.erb
<% if @question.errors.any? %>
    $(".question-form .errors").html('');
    <% @question.errors.full_messages.each do |msg| %>
        $(".question-form .errors").prepend('<%= j msg %><br />');
    <% end %>
<% else %>
    $(window.location.replace("/questions/<%= @question.id %>"));
    current_user = $(".variables").data('user-id');
    if (current_user == <%= @question.id %>) {

    }
    <% publish_to '/questions/index' do %>
        $('.questions').prepend('<%= j render @question %>');
    <% end %>
<% end %>

app/views/questions/index.html.slim
.container-fluid
  h3 Последние вопросы
  .questions
  = render @questions

= subscribe_to "/questions/index"

app/views/questions/new.html.slim
.row
  .col-md-4.col-md-offset-4
    .question-form
      .errors
      = form_for @question, remote: true do |f|
        h3 Задать свой вопрос
        br
        .form-group
          = f.label :title, 'Сформулируйте суть своего вопроса'
          = f.text_field :title, class: 'form-control'
        .form-group
          = f.label :body, 'Опишите подробно свой вопрос'
          = f.text_area :body, class: 'form-control'
        = f.fields_for :attachments, @question.attachments.build do |a|
          .form-group
            = render 'questions/attachment_fields', :f => a
            = link_to_add_association 'Добавить файл', f, :attachments
        .form-group
          = f.submit 'Задать вопрос', class: 'btn btn-primary btn-sm'

app/views/questions/show.html.slim
.container-fluid
  .row.question-block
    .col-md-12
      h3.text-center
        = @question.title
        .pull-left.subscribe
          - if current_user && current_user.subscribed?(@question)
            = link_to 'Unsubscribe', question_subscribe_path(@question, current_user.subscription_for(@question)), method: :delete, remote: true
          - else
            = link_to 'Subscribe', question_subscribes_path(@question), method: :post, remote: true
      p.question-body
        = @question.body

      p
        ul
        - @question.attachments.each do |a|
          li(class="attach-id-#{a.id}" )
            = link_to a.file_identifier, a.file.url
            = link_to ' Удалить файл', attachment_path(a), class: 'btn btn-danger btn-xs', method: :delete, remote: true if can?(:destroy, a)
      .question-comments
        .comments
          = render @question.comments
        .errors
        = form_for [@question, @question.comments.build], remote: true do |f|
          .form-group
            = f.label :body, 'Комментарий'
            = f.text_area :body, class: 'form-control'
          .form-group
            = f.submit 'Сохранить'
        = link_to 'Добавить комментарий', '', class: 'add-comment-question' if current_user
    br
    .col-md-12
      ul.nav.nav-pills.navbar-left.votes
        li.likes Likes: #{@question.likes_count}
        - if can?(:create, @question.votes.build)
          li
            = link_to 'like', votes_path(question_id: @question, vote: 'up'), method: :post, remote: true, data: { type: :json }, class: 'question-like'
          li
            = link_to 'dislike', votes_path(question_id: @question, vote: 'down'), method: :post, remote: true, data: { type: :json }, class: 'question-like'
        - if can?(:destroy, @question.votes.build)
          li.cancel
            = link_to 'Отменить выбор', vote_path(question_id: @question), method: :delete, remote: true, class: 'question-cancel', data: { type: :json } if current_user.check_like(@question)
      - if can?(:update, @question)
        ul.nav.nav-pills.navbar-right
          li
            = link_to 'Редактировать', '', class: 'question-edit-link'
          - if can?(:destroy, @question)
            li
              = link_to 'Удалить вопрос', question_path(@question), method: :delete
    .col-md-12.text-center
      = form_for @question, method: :patch, html: { id: "question-edit-form" }, remote: true do |f|
        .question-error
        = f.label :body, 'Сформулируйте суть своего вопроса'
        br
        = f.text_area :body, style: 'width: 100%:'
        br
        = f.submit 'Сохранить'


  .answers
    = render @question.answers
  br
  - if current_user
    .row
      .col-md-4.col-md-offset-4.main-answer
        .answer-errors
        = form_for [@question, @answer], remote: true, method: :post do |f|
          h4 Добавить ответ
          .form-group
            = f.label :body, "Напишите свой ответ"
            = f.text_area :body, class: 'form-control'
            = f.fields_for :attachments, @answer.attachments.build do |a|
              .form-group
                = render 'answers/attachment_fields', :f => a
                = link_to_add_association 'Добавить файл', f, :attachments
          .form-group
            = f.submit 'Ответить', class: 'btn btn-primary btn-sm'

= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to "/questions/#{@question.id}/comments"
= subscribe_to "/questions/#{@answer.id}/comments"

app/views/questions/update.js.erb
clearAlertAndNotice();
$('.question-error').html('');
<% if @question.errors.present? %>
    <% @question.errors.full_messages.each do |msg| %>
        $('.question-error').append('<%= j msg %>');
    <% end %>
    <% if flash[:alert] %>
        $('.alert').append('<br/> <%= flash[:alert] %>');
        <% flash[:alert] = '' %>
    <% end %>
<% else %>
    $('.question-body').html("<%= @question.body %>");
    $('#question-edit-form').hide();
    <% if flash[:notice] %>
        $('.notice').append('<br/> <%= flash[:notice] %>');
    <% flash[:notice] = '' %>
    <% end %>
<% end %>

answerEditLink();