config/routes.rb
Rails.application.routes.draw do
  get 'search/search'

  use_doorkeeper
  resources :attachments, only: [:destroy]

  get 'search', to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles do        
        get :me, on: :collection
      end
      resources :questions
      resources :answers
    end
  end
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post 'email_confirmation', to: 'omniauth_callbacks#email_confirmation'
  end
  resources :votes, only: [:create, :destroy]

  concern :commentable do
    resources :comments, only: [:create]
  end

  resources :questions, concerns: :commentable do
    resources :subscribes, only: [:create, :destroy]
    resources :answers, only: [:create, :update, :destroy], concerns: :commentable do
      post :best, on: :member
    end
  end

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Voteable
  include Attachable

  belongs_to :question
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  validates :body, :question_id, :user_id, presence: true
  validates :body, length: { minimum: 3, maximum: 1000 }

  after_create :answer_notification

  def check_best
    best = self.question.best_answer
    best.update!(best: false) if best
    self.update!(best: true)
  end

  private

  def answer_notification
    Notification.send_mail(self).deliver_later
    AnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: [:create, :best]
  before_action :find_answer, only: [:best, :destroy, :update]
  before_action :data_create, only: [:create]

  respond_to :js, only: [:update, :destroy, :best, :create]

  authorize_resource

  def create
    respond_with(@answer)
  end

  def update
    respond_with(@answer.update(answers_params))
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def best
    respond_with(@answer.check_best)
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def author_email(answer)
    User.find(answer.user_id).email
  end

  def data_create
    @answer = @question.answers.create(answers_params.merge(user: current_user))
    question_author = @question.user_id
    answer_author = @answer.user_id
    @result = { question_author: question_author, answer_author: answer_author }
  end

  def answers_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
  end

end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: [:create]
  authorize_resource

  def index
    @answers = Answer.all
    respond_with @answers
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer, serializer: AnswerSerializer
  end

  def create
    @answer = @question.answers.create(answers_params.merge(user: current_resource_owner))
    respond_with @answer
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def answers_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  .answer(class="row answer-#{answer.id}" )
    - best = 'best' if answer.best
    .col-md-10.col-md-offset-1.answer-block(class='#{best}')
      .row
        .col-md-12
          .pull-left
            span Добавлен:
            strong
              = answer.user.email
          .pull-right
            span Дата:
            strong
              = answer.created_at.strftime('%d/%m/%Y в %H:%M')
            br
            - if answer.best
              span(style='color: green;') Отмечен решением
      br
      .row
        .col-md-12(class='answer-body-#{answer.id}')
          = answer.body
        br
        .col-md-12.comments
          = render answer.comments
        .col-md-12.comment-block
          - if current_user
            .errors
            = form_for(@answer.comments.build, url: question_answer_comments_path(answer.question, answer), data: { form_comment_id: "#{answer.id}" }, remote: true) do |f|
              .form-group
                = f.label :body, 'Комментарий'
                = f.text_area :body, class: 'form-control'
              .form-group
                = f.submit 'Сохранить'
            = link_to 'Добавить комментарий', '', class: 'answer-comment', data: { comment_answer_id: "#{answer.id}" }
        br
        .col-md-6
          ul
            - answer.attachments.each do |a|
              li(class="attach-id-answer-#{a.id}")
                = link_to a.file_identifier, a.file.url
                - if can?(:destroy, a)
                  = link_to ' Удалить файл', attachment_path(a), class: 'btn btn-danger btn-xs', method: :delete, remote: true 
      br
      ul.nav.nav-pills.answer-votes.pull-left(id='answer-like-#{answer.id}')
        li.likes Likes: #{answer.likes_count}
        - if can?(:create, answer.votes.build)
          li.like
            = link_to 'like', votes_path(answer_id: answer, vote: 'up'), method: :post, remote: true, data: { type: :json }, class: 'answer-like'
          li.dislike
            = link_to 'dislike', votes_path(answer_id: answer, vote: 'down'), method: :post, remote: true, data: { type: :json }, class: 'answer-like'                
          li.cancel
            = link_to 'Отменить выбор', vote_path(answer_id: answer), method: :delete, remote: true, class: 'answer-cancel', data: {type: :json} if current_user.check_like(answer)
      ul.nav.nav-pills.pull-right.answer-edit
        / - if current_user and current_user.id == answer.question.user_id && current_user.id != answer.user_id && !answer.best
        - if can?(:best, answer)
          li.best-answer
            = link_to 'Выбрать лучшим', best_question_answer_path(answer.question, answer), method: :post, remote: true
        - if can?(:update, answer)
          li.edit-links
            = link_to 'Редактировать', '', class: 'answer-edit-link', data: { answer_id: answer.id }
        - if can?(:destroy, answer)
          li.edit-links
            = link_to 'Удалить ответ', question_answer_path(@question, answer), method: :delete, remote: true, class: 'answer-delete-link'
      .row
        .col-md-12.text-center
          = form_for [answer.question, answer], method: :patch, remote: true do |f|
            .answer-error
            = f.label :body, 'Ответ'
            br
            = f.text_area :body
            br
            = f.submit 'Сохранить'

app/views/answers/_attachment_fields.html.slim
.form-group(style="padding: 10px; border: 1px solid #cccccc; border-radius: 10px;" )
  .field
    = f.label :file, 'Файл'
    = f.file_field :file
  = link_to_remove_association "удалить файл", f

app/views/answers/best.js.erb
clearAlertAndNotice();
$('.answers').html('<%= j render @question.answers.order(best: 'DESC') %>');
<% if flash[:notice] %>
    $('.notice').append('<br/> <%= flash[:notice] %>');
    <% flash[:notice] = '' %>
<% end %>

questionlike();
questionCancel();
answerLike();
answerCancel();
answerEditLink();

app/views/answers/create.js.erb
clearAlertAndNotice();
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |msg| %>
        $('.answer-errors').append('<%= j msg %>');
    <% end %>
    <% if flash[:alert] %>
        $('.alert').append('<%= flash[:alert] %>');
        <%= flash[:alert] = '' %>
    <% end %>
<% else %>
    <% if flash[:notice] %>
        $('.notice').append('<%= flash[:notice] %>');
        <%= flash[:notice] = '' %>
    <% end %>
    $('.main-answer #answer_body').val('');
    <% publish_to "/questions/#{@question.id}/answers" do %>
        $('.answers').append('<%= j render @answer %>');
        current_user = $(".variables").data('user-id');
        if (!current_user) {
            $(".answer-<%= @answer.id %> .answer-edit").remove();
            $(".answer-<%= @answer.id %> .answer-comment").remove();
        }
        if (current_user == <%= @question.user_id %> && current_user != <%= @answer.user_id %>) {
            $(".answer-<%= @answer.id %> .answer-edit .edit-links").remove();
            $(".answer-<%= @answer.id %> .answer-edit").prepend('<li class="best_answer"><a data-remote="true" rel="nofollow" data-method="post" href="/questions/<%= @question.id %>/answers/<%= @answer.id %>/best">Выбрать лучшим</a></li>');
        }
        if (current_user != <%= @question.user_id %> && current_user != <%= @answer.user_id %>) {
            $(".answer-<%= @answer.id %> .answer-edit").remove();
            $("#answer-like-<%= @answer.id %>").append('<li class="like"><a data-type="json" class="answer-like" data-remote="true" rel="nofollow" data-method="post" href="/votes?answer_id=<%= @answer.id %>&amp;vote=up">like</a></li>');
            $("#answer-like-<%= @answer.id %>").append('<li class="dislike"><a data-type="json" class="answer-like" data-remote="true" rel="nofollow" data-method="post" href="/votes?answer_id=<%= @answer.id %>&amp;vote=down">dislike</a></li>');
            $("#answer-like-<%= @answer.id %>").append('<li class="cancel"><a class="answer-cancel" data-type="json" data-remote="true" rel="nofollow" data-method="delete" href="/votes/1?answer_id=<%= @answer.id %>">Отменить выбор</a></li>');
        }
        questionlike();
        questionCancel();
        answerLike();
        answerCancel();
    <% end %>


<% end %>
questionlike();
questionCancel();
answerLike();
answerCancel();
questionEditLink();
answerEditLink();
addCommentAnswer();

app/views/answers/destroy.js.erb
clearAlertAndNotice();
<% if flash[:alert] %>
    $('.alert').append('<%= j flash[:alert] %>');
<% else %>
    $('.notice').append('<%= j flash[:notice] %>');
    <%= flash[:notice] = '' %>
    $(".answer-<%= @answer.id %>").remove();
<% end %>

questionEditLink();
answerEditLink();

app/views/answers/update.js.erb
clearAlertAndNotice();
$('#edit_answer_<%= @answer.id %> .answer-error').html('');
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |msg| %>
        $('#edit_answer_<%= @answer.id %> .answer-error').append('<%= msg %> <br/>');
    <% end %>
    <% if flash[:alert] %>
        $('.alert').append('<br/> <%= flash[:alert] %>');
        <% flash[:alert] = '' %>
    <% end %>
<% else %>
    $('.answer-body-<%= @answer.id %>').html('<%= @answer.body %>');
    $('#edit_answer_<%= @answer.id %>').hide();
    <% if flash[:notice] %>
        $('.notice').append('<br/> <%= flash[:notice] %>');
        <% flash[:notice] = '' %>
    <% end %>
    $('.answer-delete-link').show();
    answerEditLink();
<% end %>